In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot
import os
import warnings
warnings.filterwarnings('ignore')

os.chdir("C:\\Users\\khush\\OneDrive\\Documents\\")
os.getcwd()

'C:\\Users\\khush\\OneDrive\\Documents'

In [42]:
readFile = pd.read_csv("audi.csv")
print(readFile)

      model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...    ...          ...      ...      ...  ...   ...         ...
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020  17199       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 9 columns]


In [43]:
# Data analysis manually.
display(len(readFile))# length of data(tottal number of columns)

10668

In [44]:
display(readFile.shape)# total 10688 rows and 9 columns.

(10668, 9)

In [45]:
print(readFile.dtypes)# type of all columns.

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object


In [46]:
print(readFile.isna().sum())#as there is no null values hence it returns zero.

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64


In [47]:
print(readFile.info())# return some info about rows info like number of non null rows in column and data type.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10668 entries, 0 to 10667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10668 non-null  object 
 1   year          10668 non-null  int64  
 2   price         10668 non-null  int64  
 3   transmission  10668 non-null  object 
 4   mileage       10668 non-null  int64  
 5   fuelType      10668 non-null  object 
 6   tax           10668 non-null  int64  
 7   mpg           10668 non-null  float64
 8   engineSize    10668 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 750.2+ KB
None


In [48]:
print(readFile.describe())#it give description about all numerical column.description about count,mean,min,max,25%..etc.

               year          price        mileage           tax           mpg  \
count  10668.000000   10668.000000   10668.000000  10668.000000  10668.000000   
mean    2017.100675   22896.685039   24827.244001    126.011436     50.770022   
std        2.167494   11714.841888   23505.257205     67.170294     12.949782   
min     1997.000000    1490.000000       1.000000      0.000000     18.900000   
25%     2016.000000   15130.750000    5968.750000    125.000000     40.900000   
50%     2017.000000   20200.000000   19000.000000    145.000000     49.600000   
75%     2019.000000   27990.000000   36464.500000    145.000000     58.900000   
max     2020.000000  145000.000000  323000.000000    580.000000    188.300000   

         engineSize  
count  10668.000000  
mean       1.930709  
std        0.602957  
min        0.000000  
25%        1.500000  
50%        2.000000  
75%        2.000000  
max        6.300000  


In [49]:
#now we divide our dataframe into dependent and independent variable.
x = readFile.iloc[:,[0,1,3,4,5,6,7,8]].values#independepent variable
display(x)

array([[' A1', 2017, 'Manual', ..., 150, 55.4, 1.4],
       [' A6', 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [' A1', 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [' A3', 2020, 'Manual', ..., 150, 49.6, 1.0],
       [' Q3', 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [' Q3', 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [50]:
y = readFile.iloc[:,[2]].values#dependent variable.
display(y)

array([[12500],
       [16500],
       [11000],
       ...,
       [17199],
       [19499],
       [15999]], dtype=int64)

In [51]:
# Since transmission,model and fuel type columns values are string type i will do label and one hot encoding.

from sklearn.preprocessing import LabelEncoder # here we have done label encoding in model and fuel type column only as model 
#have various variation and if we do oneHotEncoding various new column generated.
le_1 = LabelEncoder()
le_2 = LabelEncoder()
x[:,0] = le_1.fit_transform(x[:,0])
x[:,-4] = le_2.fit_transform(x[:,-4])
display(x)

array([[0, 2017, 'Manual', ..., 150, 55.4, 1.4],
       [5, 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [0, 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [2, 2020, 'Manual', ..., 150, 49.6, 1.0],
       [9, 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [9, 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [52]:
# one hot encoding on transmission type.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

OHE = ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[2])],remainder="passthrough")
x = OHE.fit_transform(x)
display(pd.DataFrame(x))

0    1    2  3     4      5  6    7     8    9
0      0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2      0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4      0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  0.0  1.0  0.0  2  2020   4018  2  145  49.6  1.0
10664  0.0  1.0  0.0  2  2020   1978  2  150  49.6  1.0
10665  0.0  1.0  0.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  0.0  1.0  0.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 10 columns]

In [53]:
from sklearn.preprocessing import StandardScaler

st_sc = StandardScaler()
x = st_sc.fit_transform(x)
display(pd.DataFrame(x))

0         1         2         3         4         5         6  \
0     -0.583268  1.200728 -0.712333 -1.123544 -0.046450 -0.386836  1.050783   
1      1.714479 -0.832828 -0.712333 -0.160831 -0.507834  0.483989 -0.954181   
2     -0.583268  1.200728 -0.712333 -1.123544 -0.507834  0.217781  1.050783   
3      1.714479 -0.832828 -0.712333 -0.545916 -0.046450  0.047853 -0.954181   
4     -0.583268  1.200728 -0.712333 -0.738459  0.876318 -0.971285  1.050783   
...         ...       ...       ...       ...       ...       ...       ...   
10663 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.885343  1.050783   
10664 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.972136  1.050783   
10665 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -1.030381  1.050783   
10666  1.714479 -0.832828 -0.712333  0.609339 -0.046450 -0.688442  1.050783   
10667 -0.583268  1.200728 -0.712333  0.609339 -0.507834 -0.551913  1.050783   

              7         8         9  
0      0.357147  0.357550 -0.880218  
1     -1.578323  1.037130  0.114925  
2     -1.429440  0.357550 -0.880218  
3      0.282706  1.276528  0.114925  
4      0.282706 -0.090355 -1.543647  
...         ...       ...       ...  
10663  0.282706 -0.090355 -1.543647  
10664  0.357147 -0.090355 -1.543647  
10665  0.357147 -0.090355 -1.543647  
10666  0.357147 -0.221637 -0.880218  
10667  0.357147 -0.221637 -0.880218  

[10668 rows x 10 columns]

In [54]:
# spit  the data set into 2 parts test and train part.
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
print("The number of rows and column in x")
print(x.shape)
print("The number of rows and column in y")
print(y.shape)
print("The number of rows and column in x_train")
print(x_train.shape)
print("The number of rows and column in y_train")
print(y_train.shape)
print("The number of rows and column in x_test")
print(x_test.shape)
print("The number of rows and column in y_test")
print(y_test.shape)

The number of rows and column in x
(10668, 10)
The number of rows and column in y
(10668, 1)
The number of rows and column in x_train
(7467, 10)
The number of rows and column in y_train
(7467, 1)
The number of rows and column in x_test
(3201, 10)
The number of rows and column in y_test
(3201, 1)


In [55]:
# now I make various models and predict price using them on "x" and make pridiction for "y" 
#which is price of cars and than we check the accuracy of the prediction.

# 1st is Random forest regressor.

from sklearn.ensemble import RandomForestRegressor

RFR =  RandomForestRegressor()
RFR.fit(x_train,y_train)
print(RFR)

RandomForestRegressor()


In [56]:
# Now make prediction with test data.
y_pred = RFR.predict(x_test)
print(y_pred)

[42138.53 17344.23 23051.55 ... 34338.03 10478.65 16418.97]


In [57]:
#Here we display actual and predicted price in a single dataFrame.
result = pd.concat([readFile,pd.DataFrame(y_pred,columns=["Predicted price"])],axis=1)
print(result)

      model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Predicted price  
0             1.4         42138.53  
1             2.0         17344.23  
2             1.4         23051.55  
3          

In [58]:

from sklearn.metrics import r2_score , mean_absolute_error
print("The accuracy of the prediction is",r2_score(y_test,y_pred))
print("The mean error is", mean_absolute_error(y_test,y_pred))

The accuracy of the prediction is 0.9589242178910091
The mean error is 1530.0768898961003


In [59]:
#Now we use Linear Regression model.

from sklearn.linear_model import LinearRegression

LR =   LinearRegression()
LR.fit(x_train,y_train)
print(LR)

LinearRegression()


In [60]:
# Now make prediction with test data.
y_pred = LR.predict(x_test)
print(y_pred)

[[43679.29449683]
 [18927.29449683]
 [29575.29449683]
 ...
 [34671.29449683]
 [ 8031.29449683]
 [17303.29449683]]


In [61]:
#Here we display actual and predicted price in a single dataFrame.
result = pd.concat([readFile,pd.DataFrame(y_pred,columns=["Predicted price"])],axis=1)
print(result)

      model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Predicted price  
0             1.4     43679.294497  
1             2.0     18927.294497  
2             1.4     29575.294497  
3          

In [62]:
from sklearn.metrics import r2_score , mean_absolute_error
print("The accuracy of the prediction is",r2_score(y_test,y_pred))
print("The mean error is", mean_absolute_error(y_test,y_pred))

The accuracy of the prediction is 0.7890438427223287
The mean error is 3247.5977591007195


In [63]:
#In Linear regression accuracy is less as compare to radnom forest.

In [64]:
# Creating model using extra tree regressor.
from sklearn.ensemble import ExtraTreesRegressor

ETR =   ExtraTreesRegressor()
ETR.fit(x_train,y_train)
print(ETR)


ExtraTreesRegressor()


In [65]:
# Now make prediction with test data.
y_pred = ETR.predict(x_test)
print(y_pred)

[43090.82 16969.12 22590.55 ... 34686.43 10284.45 16753.18]


In [66]:
#Here we display actual and predicted price in a single dataFrame.
result = pd.concat([readFile,pd.DataFrame(y_pred,columns=["Predicted price"])],axis=1)
print(result)

      model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Predicted price  
0             1.4         43090.82  
1             2.0         16969.12  
2             1.4         22590.55  
3          

In [67]:
from sklearn.metrics import r2_score , mean_absolute_error
print("The accuracy of the prediction is",r2_score(y_test,y_pred))
print("The mean error is", mean_absolute_error(y_test,y_pred))

The accuracy of the prediction is 0.9589006188152022
The mean error is 1536.688216338644


In [68]:
#here accuracy is good.


In [69]:
#Randomized Search CV.
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start = 80, stop = 1500, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(6, 45, num = 5)]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10]



In [70]:
rand_grid={'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf
          }



In [71]:
rf=RandomForestRegressor()

rCV=RandomizedSearchCV(estimator=rf,param_distributions=rand_grid,scoring='neg_mean_squared_error',n_iter=3,cv=3,random_state=42, n_jobs = 1)


In [ ]:
display (rCV.fit(x_train,y_train))


In [ ]:
rf_pred=rCV.predict(x_test)
display (rf_pred)


In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print('MAE',mean_absolute_error(y_test,rf_pred))
print('MSE',mean_squared_error(y_test,rf_pred))



In [ ]:
display (r2_score(Y_test,rf_pred))


In [ ]:
from catboost import CatBoostRegressor
CBR =   ExtraTreesRegressor()
CBR.fit(x_train,y_train)
print(CBR)

In [ ]:
# Now make prediction with test data.
y_pred = CBR.predict(x_test)
print(y_pred)

In [ ]:
#Here we display actual and predicted price in a single dataFrame.
result = pd.concat([readFile,pd.DataFrame(y_pred,columns=["Predicted price"])],axis=1)
print(result)

In [ ]:
from sklearn.metrics import r2_score , mean_absolute_error
print("The accuracy of the prediction is",r2_score(y_test,y_pred))
print("The mean error is", mean_absolute_error(y_test,y_pred))